api-key: "Replace this string with your API key taken from your OpenAI account"
model: "gpt-3.5-turbo"
quick_context: "You give concise, short answers to questions in ideally no more than 30 words, unless instructed to expand on your answer."
verbose_context: "You are a helpful assistant"
temperature: 1
